# Linux System Monitor - default configuration
# Override by creating ~/.config/linux-system-monitor/config.properties

net.interface=enp9s0
gpu.drm.path=/sys/class/drm/card1
disk.sata.device=/dev/sda
fs.mountpoints=/,/home,/data
poll.interval.default=2
poll.interval.filesystem=60
poll.interval.disk.temp=15

# valid values: KBps, MBps, GB/s, Kbps, Mbps, Gbps
network.speed.unit=Kbps

# chart colours
chart.color.cpu=#0A6FC2
chart.color.gpu=#F44336
chart.color.vram=#FF9800
chart.color.nvme=#9E9E9E
chart.color.sata=#607D8B
chart.color.memory.used=#2EB82E
chart.color.swap.used=#FFCCFF
chart.color.cpu.clocks=#0A305C,#0D3C73,#0F488A,#1254A1,#1461B8,#176DCF,#176DCF,#3086E8,#4794EB,#5EA1ED,#75AEF0.#8CBCF2,#A3C9F5,#BAD7F7,#D1E4FA,#E8F2FC